### ISSUE TITLE
Build target "env variables" and compiler-level conditionals

### ISSUE THREAD

**Issue by matpratta** [wolfe-labs/DU-LuaC#24]
The idea here is to introduce compiler-level conditionals, which would allow pieces of the Lua source to be added or ignored, based on a set of "environment variables" set in the `project.json` file, more specifically under each build target.

For example, let's say we have the "development" build target, under which the following is added:
```json
{
  "environment": {
    "debug": true,
    "test": "some value"
  }
}
```

Now, insider our code, we can have something like this:
```lua
--#IF debug
system.print('debug is enabled')
--#ENDIF

--#IF test "some value"
system.print('some value provided')
--#ENDIF
```

In the example above, whenever `environment.debug` exists and is true, the first block will be added to the source code, while for the second block, whenever `environment.test` matches "some value", the second block will be added to the source code.

**Comment by leniver** [comment]
This is a very good idea.
I'm currently working on a Lua-based detection system for environments.

Here is the skeleton I use for my applications
https://github.com/leniver/du-lua-template/tree/master

As you can see in the code, if debug is "true" I am loading file from the disk.
Not sure if I would use more than a single boolean. 

```
--#IF development
system.print('debug is enable')
--#ENDIF
```

In my case, I use different variables in Lua depending on development and production. As the 'testing' stage is mainly done in-game, I use 'exported' variables to help me with development/testing.
I would certainly use this condition to prevent the exposure of these variables.

**Comment by matpratta** [comment]
Pushed the first pieces of code for this.

- Changed syntax to `---@if` instead of `--#IF`;
- Added new `variables` optional property inside build targets;
- Added new `--var:` prefix to the command-line, allowing to override build target values;

@leniver it should be possible to do it with the code in the development branch, it will run in a new directive pre-processing step, essentially transparent to the existing `require` handling code, which should avoid leaking your testing stuff or shipping debug functions in production scripts.

If you want to try it out, make sure you pull the code from that branch locally and build it with `npm run build`.
