### ISSUE TITLE
Feature: Support embedding of compiled Lua files

### ISSUE THREAD

**Issue by matpratta** [wolfe-labs/DU-LuaC#28]
We currently have `library.embedFile` which basically takes a file from the current directory and embeds it as a Lua literal, it's quite helpful to embed data like render scripts, but I'd like to take it a bit further.

The idea is to add something like `library.embedLua` (accepting name suggestions) where it would take a build by its name (or maybe any Lua file? what could go wrong?), do all the processing from `du-lua build` for that build and then embed its resulting Lua into the code.

This would make it possible to embed Lua render scripts that make use of `require` statements to import render script specific libraries, plus also allowing for code minification on embedded Lua files.

**Comment by tobitege** [comment]
That'd certainly be a very pro feature, I still have to wrap my mind around the possibilities this would offer. 👍

**Comment by matpratta** [comment]
Implemented in a98a25bd1e8c161ce680687eca8b156ac842dcbc
