### ISSUE TITLE
embedFile(): use same file resolving method as require()

### ISSUE THREAD

**Issue by tobitege** [wolfe-labs/DU-LuaC#30]
The compiler uses the LUA_PATH for resolving filenames for the require() command.
However, the embedFile() only seems to try to find the file in the same directory where called from.
It would be helpful and consistent if embedFile would use the same filename resolving mechanism as e.g. renderscripts could be located in their own location.

Looked in the source for it:
In src/compiler_functions.ts -> export default class LibraryEmbedFileFunction -> invoke
should equally use "getRequiredFileInfo()" method (in DULuaCompiler.ts)

**Comment by matpratta** [comment]
Fixed in 2ad91041f23158f1316dd20ec7f123db2df4618e
